# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Tom Liu's Blog
subtitle: 'Since September 2025'
description: 'Pour que tu ne te perdes pas.'
keywords: 'research, personal, portfolio, blog, technology'
author: Tom Liu
language: en
timezone: 'America/New_York'  # Update this to your timezone

# URL
## Update this to your Netlify URL once deployed
url: https://liutom.netlify.app  # Change 'tomliu' to your preferred subdomain
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true  # Changed to true for better image handling
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: 'archives'  # Move blog index to /archives
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
  - '.DS_Store'
  - 'Thumbs.db'
  - '.git/**'
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## For Netlify, you don't need this section, but keeping it empty is fine
deploy:
  type: ''

# Feed (RSS) - Optional but recommended
## You'll need to install: npm install hexo-generator-feed --save
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  
# Sitemap - Optional but recommended for SEO
## You'll need to install: npm install hexo-generator-sitemap --save
sitemap:
  path: sitemap.xml